project_name: example
databases:
- name: duckdb-jaffle-shop
  templates:
  - columns
  - preview
  profiling:
    refresh_policy: "interval" # "always", "interval", or "once"
    interval_days: 1
  include: []
  exclude: []
  type: duckdb
  path: ./jaffle_shop.duckdb
repos:
- name: dbt
  url: https://github.com/getnao/jaffle_shop_duckdb.git
  branch: null
semantic_layer:
  type: metricflow
  manifest_path: ./repos/dbt/target/semantic_manifest.json
  database: duckdb-jaffle-shop
notion: null
llm: null
slack: null
