{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "nao.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nao.labels" . | nindent 4 }}
  {{- with (include "nao.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "nao.selectorLabels" . | nindent 6 }}
{{- end }}