"""Unit tests for sync markers helpers."""

from __future__ import annotations

from nao_core.commands.sync.markers import (
    ContextFileKind,
    ensure_annotations_file,
    kind_of,
    marker_for,
    with_generated_marker,
)

GENERATED_MESSAGE = "This file is managed and generated by the agent, do not modify it!"
MANUAL_MESSAGE = "These are manual notes you want the agent to keep in mind, safe to edit."


def test_marker_for_generated_has_token_and_message():
    marker = marker_for(ContextFileKind.GENERATED)

    assert marker == f"---\ntype: generated\ncomment: {GENERATED_MESSAGE}\n---"


def test_marker_for_manual_has_token_and_message():
    marker = marker_for(ContextFileKind.MANUAL)

    assert marker == f"---\ntype: manual\ncomment: {MANUAL_MESSAGE}\n---"


def test_with_generated_marker_prepends_marker_and_preserves_content():
    content = "# users\n\nSome rendered content."
    result = with_generated_marker(content)

    generated_marker = marker_for(ContextFileKind.GENERATED)
    assert result.startswith(generated_marker)
    assert result == f"{generated_marker}\n\n{content}"
    assert content in result


def test_ensure_annotations_file_creates_file_when_missing(tmp_path):
    ensure_annotations_file(tmp_path)

    annotations_file = tmp_path / "annotations.md"
    assert annotations_file.exists()
    assert annotations_file.read_text() == f"{marker_for(ContextFileKind.MANUAL)}\n"


def test_ensure_annotations_file_never_overwrites_existing(tmp_path):
    annotations_file = tmp_path / "annotations.md"
    custom_content = "My own notes that must survive syncs.\n"
    annotations_file.write_text(custom_content)

    ensure_annotations_file(tmp_path)

    assert annotations_file.read_text() == custom_content


def test_kind_of_detects_generated_content():
    content = with_generated_marker("# users\n\nSome content.")

    assert kind_of(content) is ContextFileKind.GENERATED


def test_kind_of_detects_manual_content(tmp_path):
    ensure_annotations_file(tmp_path)
    content = (tmp_path / "annotations.md").read_text()

    assert kind_of(content) is ContextFileKind.MANUAL


def test_kind_of_returns_none_without_marker():
    assert kind_of("# users\n\nJust some content, no marker.") is None
