"""Markers for agent-managed and manual context files written during sync."""

from __future__ import annotations

from enum import Enum
from pathlib import Path

import yaml


class ContextFileKind(str, Enum):
    """Origin of a context file written during sync."""

    GENERATED = "generated"
    MANUAL = "manual"


_MESSAGES: dict[ContextFileKind, str] = {
    ContextFileKind.GENERATED: "This file is managed and generated by the agent, do not modify it!",
    ContextFileKind.MANUAL: "These are manual notes you want the agent to keep in mind, safe to edit.",
}


def marker_for(kind: ContextFileKind) -> str:
    """Build the YAML frontmatter header carrying the file kind and human message."""
    return f"---\ntype: {kind.value}\ncomment: {_MESSAGES[kind]}\n---"


def kind_of(content: str) -> ContextFileKind | None:
    """Classify a file from its frontmatter `type`, or None when absent/unknown."""
    if not content.startswith("---"):
        return None
    parts = content.split("---", 2)
    if len(parts) < 3:
        return None
    try:
        meta = yaml.safe_load(parts[1]) or {}
    except yaml.YAMLError:
        return None
    try:
        return ContextFileKind(meta.get("type"))
    except ValueError:
        return None


def with_generated_marker(content: str) -> str:
    """Prepend the generated-file marker to freshly rendered content."""
    return f"{marker_for(ContextFileKind.GENERATED)}\n\n{content}"


def ensure_annotations_file(folder: Path) -> None:
    """Create the annotations file in a table folder once, never overwriting it."""
    annotations_file = folder / "annotations.md"
    if annotations_file.exists():
        return
    annotations_file.write_text(f"{marker_for(ContextFileKind.MANUAL)}\n")
