/**
 * Classifies nao project files as auto-generated or human-written.
 *
 * `nao sync` regenerates `databases/**` (from warehouse metadata + templates) and
 * `repos/**` (cloned source repos) on every run, so any edit to those is lost. The
 * remaining context (RULES.md, semantics, docs, queries, agent config, nao_config.yaml)
 * is authored by humans and is the only safe target for an automated pull request.
 */

/** Top-level folders whose contents are regenerated by `nao sync`. */
const GENERATED_DIRS = ['databases', 'repos'] as const;

/** Files/globs that are tooling artifacts and should never be edited automatically. */
const GENERATED_FILES = ['templates/', 'tests/'] as const;

/** Strips a leading `./` and normalizes Windows separators so paths compare consistently. */
export function normalizeContextPath(filePath: string): string {
	return filePath.replace(/\\/g, '/').replace(/^\.?\//, '');
}

/** True when the file is (re)generated by `nao sync` and must not be edited directly. */
function isGeneratedContextPath(filePath: string): boolean {
	const normalized = normalizeContextPath(filePath);
	if (GENERATED_DIRS.some((dir) => normalized === dir || normalized.startsWith(`${dir}/`))) {
		return true;
	}
	return GENERATED_FILES.some((prefix) => normalized.startsWith(prefix));
}

/** True when the file is human-written and safe to include in an automated PR. */
export function isHumanWritableContextPath(filePath: string): boolean {
	return !isGeneratedContextPath(filePath);
}
