/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as EmbedRouteImport } from './routes/embed'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as SidebarLayoutRouteImport } from './routes/_sidebar-layout'
import { Route as SidebarLayoutSettingsRouteImport } from './routes/_sidebar-layout.settings'
import { Route as SidebarLayoutChatLayoutRouteImport } from './routes/_sidebar-layout._chat-layout'
import { Route as SidebarLayoutStoriesIndexRouteImport } from './routes/_sidebar-layout.stories.index'
import { Route as SidebarLayoutSettingsIndexRouteImport } from './routes/_sidebar-layout.settings.index'
import { Route as SidebarLayoutFeedIndexRouteImport } from './routes/_sidebar-layout.feed.index'
import { Route as SidebarLayoutChatLayoutIndexRouteImport } from './routes/_sidebar-layout._chat-layout.index'
import { Route as EmbedStoryStoryIdRouteImport } from './routes/embed.story.$storyId'
import { Route as EmbedMapMapEmbedIdRouteImport } from './routes/embed.map.$mapEmbedId'
import { Route as EmbedChartChartEmbedIdRouteImport } from './routes/embed.chart.$chartEmbedId'
import { Route as SidebarLayoutSharedChatShareIdRouteImport } from './routes/_sidebar-layout.shared-chat.$shareId'
import { Route as SidebarLayoutSettingsWhiteLabelRouteImport } from './routes/_sidebar-layout.settings.white-label'
import { Route as SidebarLayoutSettingsUsageRouteImport } from './routes/_sidebar-layout.settings.usage'
import { Route as SidebarLayoutSettingsStorageRouteImport } from './routes/_sidebar-layout.settings.storage'
import { Route as SidebarLayoutSettingsRecommendationsRouteImport } from './routes/_sidebar-layout.settings.recommendations'
import { Route as SidebarLayoutSettingsProjectRouteImport } from './routes/_sidebar-layout.settings.project'
import { Route as SidebarLayoutSettingsOrganizationRouteImport } from './routes/_sidebar-layout.settings.organization'
import { Route as SidebarLayoutSettingsMemoryRouteImport } from './routes/_sidebar-layout.settings.memory'
import { Route as SidebarLayoutSettingsMcpEndpointRouteImport } from './routes/_sidebar-layout.settings.mcp-endpoint'
import { Route as SidebarLayoutSettingsLogsRouteImport } from './routes/_sidebar-layout.settings.logs'
import { Route as SidebarLayoutSettingsGitRouteImport } from './routes/_sidebar-layout.settings.git'
import { Route as SidebarLayoutSettingsEnterpriseRouteImport } from './routes/_sidebar-layout.settings.enterprise'
import { Route as SidebarLayoutSettingsContextExplorerRouteImport } from './routes/_sidebar-layout.settings.context-explorer'
import { Route as SidebarLayoutSettingsAppearanceRouteImport } from './routes/_sidebar-layout.settings.appearance'
import { Route as SidebarLayoutSettingsAccountRouteImport } from './routes/_sidebar-layout.settings.account'
import { Route as SidebarLayoutAutomationsAutomationIdRouteImport } from './routes/_sidebar-layout.automations.$automationId'
import { Route as SidebarLayoutChatLayoutChatIdRouteImport } from './routes/_sidebar-layout._chat-layout.$chatId'
import { Route as SidebarLayoutSettingsProjectIndexRouteImport } from './routes/_sidebar-layout.settings.project.index'
import { Route as SidebarLayoutSettingsOrganizationIndexRouteImport } from './routes/_sidebar-layout.settings.organization.index'
import { Route as SidebarLayoutStoriesStandaloneStoryIdRouteImport } from './routes/_sidebar-layout.stories.standalone.$storyId'
import { Route as SidebarLayoutStoriesSharedShareIdRouteImport } from './routes/_sidebar-layout.stories.shared.$shareId'
import { Route as SidebarLayoutSettingsProjectWhatsappRouteImport } from './routes/_sidebar-layout.settings.project.whatsapp'
import { Route as SidebarLayoutSettingsProjectTelegramRouteImport } from './routes/_sidebar-layout.settings.project.telegram'
import { Route as SidebarLayoutSettingsProjectTeamsRouteImport } from './routes/_sidebar-layout.settings.project.teams'
import { Route as SidebarLayoutSettingsProjectTeamRouteImport } from './routes/_sidebar-layout.settings.project.team'
import { Route as SidebarLayoutSettingsProjectSlackRouteImport } from './routes/_sidebar-layout.settings.project.slack'
import { Route as SidebarLayoutSettingsProjectModelsRouteImport } from './routes/_sidebar-layout.settings.project.models'
import { Route as SidebarLayoutSettingsProjectMcpServersRouteImport } from './routes/_sidebar-layout.settings.project.mcp-servers'
import { Route as SidebarLayoutSettingsProjectMcpEndpointRouteImport } from './routes/_sidebar-layout.settings.project.mcp-endpoint'
import { Route as SidebarLayoutSettingsProjectMcpRouteImport } from './routes/_sidebar-layout.settings.project.mcp'
import { Route as SidebarLayoutSettingsProjectMattermostRouteImport } from './routes/_sidebar-layout.settings.project.mattermost'
import { Route as SidebarLayoutSettingsProjectIntegrationsRouteImport } from './routes/_sidebar-layout.settings.project.integrations'
import { Route as SidebarLayoutSettingsProjectBudgetsRouteImport } from './routes/_sidebar-layout.settings.project.budgets'
import { Route as SidebarLayoutSettingsProjectAgentRouteImport } from './routes/_sidebar-layout.settings.project.agent'
import { Route as SidebarLayoutSettingsOrganizationMembersRouteImport } from './routes/_sidebar-layout.settings.organization.members'
import { Route as SidebarLayoutSettingsProjectIntegrationsIndexRouteImport } from './routes/_sidebar-layout.settings.project.integrations.index'
import { Route as SidebarLayoutStoriesPreviewChatIdStorySlugRouteImport } from './routes/_sidebar-layout.stories.preview.$chatId.$storySlug'
import { Route as SidebarLayoutSettingsUsageReplayChatIdRouteImport } from './routes/_sidebar-layout.settings.usage.replay.$chatId'
import { Route as SidebarLayoutSettingsProjectIntegrationsIntegrationIdRouteImport } from './routes/_sidebar-layout.settings.project.integrations.$integrationId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedRoute = EmbedRouteImport.update({
  id: '/embed',
  path: '/embed',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarLayoutRoute = SidebarLayoutRouteImport.update({
  id: '/_sidebar-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarLayoutSettingsRoute = SidebarLayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SidebarLayoutRoute,
} as any)
const SidebarLayoutChatLayoutRoute = SidebarLayoutChatLayoutRouteImport.update({
  id: '/_chat-layout',
  getParentRoute: () => SidebarLayoutRoute,
} as any)
const SidebarLayoutStoriesIndexRoute =
  SidebarLayoutStoriesIndexRouteImport.update({
    id: '/stories/',
    path: '/stories/',
    getParentRoute: () => SidebarLayoutRoute,
  } as any)
const SidebarLayoutSettingsIndexRoute =
  SidebarLayoutSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SidebarLayoutSettingsRoute,
  } as any)
const SidebarLayoutFeedIndexRoute = SidebarLayoutFeedIndexRouteImport.update({
  id: '/feed/',
  path: '/feed/',
  getParentRoute: () => SidebarLayoutRoute,
} as any)
const SidebarLayoutChatLayoutIndexRoute =
  SidebarLayoutChatLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SidebarLayoutChatLayoutRoute,
  } as any)
const EmbedStoryStoryIdRoute = EmbedStoryStoryIdRouteImport.update({
  id: '/story/$storyId',
  path: '/story/$storyId',
  getParentRoute: () => EmbedRoute,
} as any)
const EmbedMapMapEmbedIdRoute = EmbedMapMapEmbedIdRouteImport.update({
  id: '/map/$mapEmbedId',
  path: '/map/$mapEmbedId',
  getParentRoute: () => EmbedRoute,
} as any)
const EmbedChartChartEmbedIdRoute = EmbedChartChartEmbedIdRouteImport.update({
  id: '/chart/$chartEmbedId',
  path: '/chart/$chartEmbedId',
  getParentRoute: () => EmbedRoute,
} as any)
const SidebarLayoutSharedChatShareIdRoute =
  SidebarLayoutSharedChatShareIdRouteImport.update({
    id: '/shared-chat/$shareId',
    path: '/shared-chat/$shareId',
    getParentRoute: () => SidebarLayoutRoute,
  } as any)
const SidebarLayoutSettingsWhiteLabelRoute =
  SidebarLayoutSettingsWhiteLabelRouteImport.update({
    id: '/white-label',
    path: '/white-label',
    getParentRoute: () => SidebarLayoutSettingsRoute,
  } as any)
const SidebarLayoutSettingsUsageRoute =
  SidebarLayoutSettingsUsageRouteImport.update({
    id: '/usage',
    path: '/usage',
    getParentRoute: () => SidebarLayoutSettingsRoute,
  } as any)
const SidebarLayoutSettingsStorageRoute =
  SidebarLayoutSettingsStorageRouteImport.update({
    id: '/storage',
    path: '/storage',
    getParentRoute: () => SidebarLayoutSettingsRoute,
  } as any)
const SidebarLayoutSettingsRecommendationsRoute =
  SidebarLayoutSettingsRecommendationsRouteImport.update({
    id: '/recommendations',
    path: '/recommendations',
    getParentRoute: () => SidebarLayoutSettingsRoute,
  } as any)
const SidebarLayoutSettingsProjectRoute =
  SidebarLayoutSettingsProjectRouteImport.update({
    id: '/project',
    path: '/project',
    getParentRoute: () => SidebarLayoutSettingsRoute,
  } as any)
const SidebarLayoutSettingsOrganizationRoute =
  SidebarLayoutSettingsOrganizationRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => SidebarLayoutSettingsRoute,
  } as any)
const SidebarLayoutSettingsMemoryRoute =
  SidebarLayoutSettingsMemoryRouteImport.update({
    id: '/memory',
    path: '/memory',
    getParentRoute: () => SidebarLayoutSettingsRoute,
  } as any)
const SidebarLayoutSettingsMcpEndpointRoute =
  SidebarLayoutSettingsMcpEndpointRouteImport.update({
    id: '/mcp-endpoint',
    path: '/mcp-endpoint',
    getParentRoute: () => SidebarLayoutSettingsRoute,
  } as any)
const SidebarLayoutSettingsLogsRoute =
  SidebarLayoutSettingsLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => SidebarLayoutSettingsRoute,
  } as any)
const SidebarLayoutSettingsGitRoute =
  SidebarLayoutSettingsGitRouteImport.update({
    id: '/git',
    path: '/git',
    getParentRoute: () => SidebarLayoutSettingsRoute,
  } as any)
const SidebarLayoutSettingsEnterpriseRoute =
  SidebarLayoutSettingsEnterpriseRouteImport.update({
    id: '/enterprise',
    path: '/enterprise',
    getParentRoute: () => SidebarLayoutSettingsRoute,
  } as any)
const SidebarLayoutSettingsContextExplorerRoute =
  SidebarLayoutSettingsContextExplorerRouteImport.update({
    id: '/context-explorer',
    path: '/context-explorer',
    getParentRoute: () => SidebarLayoutSettingsRoute,
  } as any)
const SidebarLayoutSettingsAppearanceRoute =
  SidebarLayoutSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => SidebarLayoutSettingsRoute,
  } as any)
const SidebarLayoutSettingsAccountRoute =
  SidebarLayoutSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => SidebarLayoutSettingsRoute,
  } as any)
const SidebarLayoutAutomationsAutomationIdRoute =
  SidebarLayoutAutomationsAutomationIdRouteImport.update({
    id: '/automations/$automationId',
    path: '/automations/$automationId',
    getParentRoute: () => SidebarLayoutRoute,
  } as any)
const SidebarLayoutChatLayoutChatIdRoute =
  SidebarLayoutChatLayoutChatIdRouteImport.update({
    id: '/$chatId',
    path: '/$chatId',
    getParentRoute: () => SidebarLayoutChatLayoutRoute,
  } as any)
const SidebarLayoutSettingsProjectIndexRoute =
  SidebarLayoutSettingsProjectIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SidebarLayoutSettingsProjectRoute,
  } as any)
const SidebarLayoutSettingsOrganizationIndexRoute =
  SidebarLayoutSettingsOrganizationIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SidebarLayoutSettingsOrganizationRoute,
  } as any)
const SidebarLayoutStoriesStandaloneStoryIdRoute =
  SidebarLayoutStoriesStandaloneStoryIdRouteImport.update({
    id: '/stories/standalone/$storyId',
    path: '/stories/standalone/$storyId',
    getParentRoute: () => SidebarLayoutRoute,
  } as any)
const SidebarLayoutStoriesSharedShareIdRoute =
  SidebarLayoutStoriesSharedShareIdRouteImport.update({
    id: '/stories/shared/$shareId',
    path: '/stories/shared/$shareId',
    getParentRoute: () => SidebarLayoutRoute,
  } as any)
const SidebarLayoutSettingsProjectWhatsappRoute =
  SidebarLayoutSettingsProjectWhatsappRouteImport.update({
    id: '/whatsapp',
    path: '/whatsapp',
    getParentRoute: () => SidebarLayoutSettingsProjectRoute,
  } as any)
const SidebarLayoutSettingsProjectTelegramRoute =
  SidebarLayoutSettingsProjectTelegramRouteImport.update({
    id: '/telegram',
    path: '/telegram',
    getParentRoute: () => SidebarLayoutSettingsProjectRoute,
  } as any)
const SidebarLayoutSettingsProjectTeamsRoute =
  SidebarLayoutSettingsProjectTeamsRouteImport.update({
    id: '/teams',
    path: '/teams',
    getParentRoute: () => SidebarLayoutSettingsProjectRoute,
  } as any)
const SidebarLayoutSettingsProjectTeamRoute =
  SidebarLayoutSettingsProjectTeamRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => SidebarLayoutSettingsProjectRoute,
  } as any)
const SidebarLayoutSettingsProjectSlackRoute =
  SidebarLayoutSettingsProjectSlackRouteImport.update({
    id: '/slack',
    path: '/slack',
    getParentRoute: () => SidebarLayoutSettingsProjectRoute,
  } as any)
const SidebarLayoutSettingsProjectModelsRoute =
  SidebarLayoutSettingsProjectModelsRouteImport.update({
    id: '/models',
    path: '/models',
    getParentRoute: () => SidebarLayoutSettingsProjectRoute,
  } as any)
const SidebarLayoutSettingsProjectMcpServersRoute =
  SidebarLayoutSettingsProjectMcpServersRouteImport.update({
    id: '/mcp-servers',
    path: '/mcp-servers',
    getParentRoute: () => SidebarLayoutSettingsProjectRoute,
  } as any)
const SidebarLayoutSettingsProjectMcpEndpointRoute =
  SidebarLayoutSettingsProjectMcpEndpointRouteImport.update({
    id: '/mcp-endpoint',
    path: '/mcp-endpoint',
    getParentRoute: () => SidebarLayoutSettingsProjectRoute,
  } as any)
const SidebarLayoutSettingsProjectMcpRoute =
  SidebarLayoutSettingsProjectMcpRouteImport.update({
    id: '/mcp',
    path: '/mcp',
    getParentRoute: () => SidebarLayoutSettingsProjectRoute,
  } as any)
const SidebarLayoutSettingsProjectMattermostRoute =
  SidebarLayoutSettingsProjectMattermostRouteImport.update({
    id: '/mattermost',
    path: '/mattermost',
    getParentRoute: () => SidebarLayoutSettingsProjectRoute,
  } as any)
const SidebarLayoutSettingsProjectIntegrationsRoute =
  SidebarLayoutSettingsProjectIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => SidebarLayoutSettingsProjectRoute,
  } as any)
const SidebarLayoutSettingsProjectBudgetsRoute =
  SidebarLayoutSettingsProjectBudgetsRouteImport.update({
    id: '/budgets',
    path: '/budgets',
    getParentRoute: () => SidebarLayoutSettingsProjectRoute,
  } as any)
const SidebarLayoutSettingsProjectAgentRoute =
  SidebarLayoutSettingsProjectAgentRouteImport.update({
    id: '/agent',
    path: '/agent',
    getParentRoute: () => SidebarLayoutSettingsProjectRoute,
  } as any)
const SidebarLayoutSettingsOrganizationMembersRoute =
  SidebarLayoutSettingsOrganizationMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => SidebarLayoutSettingsOrganizationRoute,
  } as any)
const SidebarLayoutSettingsProjectIntegrationsIndexRoute =
  SidebarLayoutSettingsProjectIntegrationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SidebarLayoutSettingsProjectIntegrationsRoute,
  } as any)
const SidebarLayoutStoriesPreviewChatIdStorySlugRoute =
  SidebarLayoutStoriesPreviewChatIdStorySlugRouteImport.update({
    id: '/stories/preview/$chatId/$storySlug',
    path: '/stories/preview/$chatId/$storySlug',
    getParentRoute: () => SidebarLayoutRoute,
  } as any)
const SidebarLayoutSettingsUsageReplayChatIdRoute =
  SidebarLayoutSettingsUsageReplayChatIdRouteImport.update({
    id: '/replay/$chatId',
    path: '/replay/$chatId',
    getParentRoute: () => SidebarLayoutSettingsUsageRoute,
  } as any)
const SidebarLayoutSettingsProjectIntegrationsIntegrationIdRoute =
  SidebarLayoutSettingsProjectIntegrationsIntegrationIdRouteImport.update({
    id: '/$integrationId',
    path: '/$integrationId',
    getParentRoute: () => SidebarLayoutSettingsProjectIntegrationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof SidebarLayoutChatLayoutIndexRoute
  '/consent': typeof ConsentRoute
  '/embed': typeof EmbedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/settings': typeof SidebarLayoutSettingsRouteWithChildren
  '/$chatId': typeof SidebarLayoutChatLayoutChatIdRoute
  '/automations/$automationId': typeof SidebarLayoutAutomationsAutomationIdRoute
  '/settings/account': typeof SidebarLayoutSettingsAccountRoute
  '/settings/appearance': typeof SidebarLayoutSettingsAppearanceRoute
  '/settings/context-explorer': typeof SidebarLayoutSettingsContextExplorerRoute
  '/settings/enterprise': typeof SidebarLayoutSettingsEnterpriseRoute
  '/settings/git': typeof SidebarLayoutSettingsGitRoute
  '/settings/logs': typeof SidebarLayoutSettingsLogsRoute
  '/settings/mcp-endpoint': typeof SidebarLayoutSettingsMcpEndpointRoute
  '/settings/memory': typeof SidebarLayoutSettingsMemoryRoute
  '/settings/organization': typeof SidebarLayoutSettingsOrganizationRouteWithChildren
  '/settings/project': typeof SidebarLayoutSettingsProjectRouteWithChildren
  '/settings/recommendations': typeof SidebarLayoutSettingsRecommendationsRoute
  '/settings/storage': typeof SidebarLayoutSettingsStorageRoute
  '/settings/usage': typeof SidebarLayoutSettingsUsageRouteWithChildren
  '/settings/white-label': typeof SidebarLayoutSettingsWhiteLabelRoute
  '/shared-chat/$shareId': typeof SidebarLayoutSharedChatShareIdRoute
  '/embed/chart/$chartEmbedId': typeof EmbedChartChartEmbedIdRoute
  '/embed/map/$mapEmbedId': typeof EmbedMapMapEmbedIdRoute
  '/embed/story/$storyId': typeof EmbedStoryStoryIdRoute
  '/feed/': typeof SidebarLayoutFeedIndexRoute
  '/settings/': typeof SidebarLayoutSettingsIndexRoute
  '/stories/': typeof SidebarLayoutStoriesIndexRoute
  '/settings/organization/members': typeof SidebarLayoutSettingsOrganizationMembersRoute
  '/settings/project/agent': typeof SidebarLayoutSettingsProjectAgentRoute
  '/settings/project/budgets': typeof SidebarLayoutSettingsProjectBudgetsRoute
  '/settings/project/integrations': typeof SidebarLayoutSettingsProjectIntegrationsRouteWithChildren
  '/settings/project/mattermost': typeof SidebarLayoutSettingsProjectMattermostRoute
  '/settings/project/mcp': typeof SidebarLayoutSettingsProjectMcpRoute
  '/settings/project/mcp-endpoint': typeof SidebarLayoutSettingsProjectMcpEndpointRoute
  '/settings/project/mcp-servers': typeof SidebarLayoutSettingsProjectMcpServersRoute
  '/settings/project/models': typeof SidebarLayoutSettingsProjectModelsRoute
  '/settings/project/slack': typeof SidebarLayoutSettingsProjectSlackRoute
  '/settings/project/team': typeof SidebarLayoutSettingsProjectTeamRoute
  '/settings/project/teams': typeof SidebarLayoutSettingsProjectTeamsRoute
  '/settings/project/telegram': typeof SidebarLayoutSettingsProjectTelegramRoute
  '/settings/project/whatsapp': typeof SidebarLayoutSettingsProjectWhatsappRoute
  '/stories/shared/$shareId': typeof SidebarLayoutStoriesSharedShareIdRoute
  '/stories/standalone/$storyId': typeof SidebarLayoutStoriesStandaloneStoryIdRoute
  '/settings/organization/': typeof SidebarLayoutSettingsOrganizationIndexRoute
  '/settings/project/': typeof SidebarLayoutSettingsProjectIndexRoute
  '/settings/project/integrations/$integrationId': typeof SidebarLayoutSettingsProjectIntegrationsIntegrationIdRoute
  '/settings/usage/replay/$chatId': typeof SidebarLayoutSettingsUsageReplayChatIdRoute
  '/stories/preview/$chatId/$storySlug': typeof SidebarLayoutStoriesPreviewChatIdStorySlugRoute
  '/settings/project/integrations/': typeof SidebarLayoutSettingsProjectIntegrationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof SidebarLayoutChatLayoutIndexRoute
  '/consent': typeof ConsentRoute
  '/embed': typeof EmbedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/$chatId': typeof SidebarLayoutChatLayoutChatIdRoute
  '/automations/$automationId': typeof SidebarLayoutAutomationsAutomationIdRoute
  '/settings/account': typeof SidebarLayoutSettingsAccountRoute
  '/settings/appearance': typeof SidebarLayoutSettingsAppearanceRoute
  '/settings/context-explorer': typeof SidebarLayoutSettingsContextExplorerRoute
  '/settings/enterprise': typeof SidebarLayoutSettingsEnterpriseRoute
  '/settings/git': typeof SidebarLayoutSettingsGitRoute
  '/settings/logs': typeof SidebarLayoutSettingsLogsRoute
  '/settings/mcp-endpoint': typeof SidebarLayoutSettingsMcpEndpointRoute
  '/settings/memory': typeof SidebarLayoutSettingsMemoryRoute
  '/settings/recommendations': typeof SidebarLayoutSettingsRecommendationsRoute
  '/settings/storage': typeof SidebarLayoutSettingsStorageRoute
  '/settings/usage': typeof SidebarLayoutSettingsUsageRouteWithChildren
  '/settings/white-label': typeof SidebarLayoutSettingsWhiteLabelRoute
  '/shared-chat/$shareId': typeof SidebarLayoutSharedChatShareIdRoute
  '/embed/chart/$chartEmbedId': typeof EmbedChartChartEmbedIdRoute
  '/embed/map/$mapEmbedId': typeof EmbedMapMapEmbedIdRoute
  '/embed/story/$storyId': typeof EmbedStoryStoryIdRoute
  '/feed': typeof SidebarLayoutFeedIndexRoute
  '/settings': typeof SidebarLayoutSettingsIndexRoute
  '/stories': typeof SidebarLayoutStoriesIndexRoute
  '/settings/organization/members': typeof SidebarLayoutSettingsOrganizationMembersRoute
  '/settings/project/agent': typeof SidebarLayoutSettingsProjectAgentRoute
  '/settings/project/budgets': typeof SidebarLayoutSettingsProjectBudgetsRoute
  '/settings/project/mattermost': typeof SidebarLayoutSettingsProjectMattermostRoute
  '/settings/project/mcp': typeof SidebarLayoutSettingsProjectMcpRoute
  '/settings/project/mcp-endpoint': typeof SidebarLayoutSettingsProjectMcpEndpointRoute
  '/settings/project/mcp-servers': typeof SidebarLayoutSettingsProjectMcpServersRoute
  '/settings/project/models': typeof SidebarLayoutSettingsProjectModelsRoute
  '/settings/project/slack': typeof SidebarLayoutSettingsProjectSlackRoute
  '/settings/project/team': typeof SidebarLayoutSettingsProjectTeamRoute
  '/settings/project/teams': typeof SidebarLayoutSettingsProjectTeamsRoute
  '/settings/project/telegram': typeof SidebarLayoutSettingsProjectTelegramRoute
  '/settings/project/whatsapp': typeof SidebarLayoutSettingsProjectWhatsappRoute
  '/stories/shared/$shareId': typeof SidebarLayoutStoriesSharedShareIdRoute
  '/stories/standalone/$storyId': typeof SidebarLayoutStoriesStandaloneStoryIdRoute
  '/settings/organization': typeof SidebarLayoutSettingsOrganizationIndexRoute
  '/settings/project': typeof SidebarLayoutSettingsProjectIndexRoute
  '/settings/project/integrations/$integrationId': typeof SidebarLayoutSettingsProjectIntegrationsIntegrationIdRoute
  '/settings/usage/replay/$chatId': typeof SidebarLayoutSettingsUsageReplayChatIdRoute
  '/stories/preview/$chatId/$storySlug': typeof SidebarLayoutStoriesPreviewChatIdStorySlugRoute
  '/settings/project/integrations': typeof SidebarLayoutSettingsProjectIntegrationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_sidebar-layout': typeof SidebarLayoutRouteWithChildren
  '/consent': typeof ConsentRoute
  '/embed': typeof EmbedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_sidebar-layout/_chat-layout': typeof SidebarLayoutChatLayoutRouteWithChildren
  '/_sidebar-layout/settings': typeof SidebarLayoutSettingsRouteWithChildren
  '/_sidebar-layout/_chat-layout/$chatId': typeof SidebarLayoutChatLayoutChatIdRoute
  '/_sidebar-layout/automations/$automationId': typeof SidebarLayoutAutomationsAutomationIdRoute
  '/_sidebar-layout/settings/account': typeof SidebarLayoutSettingsAccountRoute
  '/_sidebar-layout/settings/appearance': typeof SidebarLayoutSettingsAppearanceRoute
  '/_sidebar-layout/settings/context-explorer': typeof SidebarLayoutSettingsContextExplorerRoute
  '/_sidebar-layout/settings/enterprise': typeof SidebarLayoutSettingsEnterpriseRoute
  '/_sidebar-layout/settings/git': typeof SidebarLayoutSettingsGitRoute
  '/_sidebar-layout/settings/logs': typeof SidebarLayoutSettingsLogsRoute
  '/_sidebar-layout/settings/mcp-endpoint': typeof SidebarLayoutSettingsMcpEndpointRoute
  '/_sidebar-layout/settings/memory': typeof SidebarLayoutSettingsMemoryRoute
  '/_sidebar-layout/settings/organization': typeof SidebarLayoutSettingsOrganizationRouteWithChildren
  '/_sidebar-layout/settings/project': typeof SidebarLayoutSettingsProjectRouteWithChildren
  '/_sidebar-layout/settings/recommendations': typeof SidebarLayoutSettingsRecommendationsRoute
  '/_sidebar-layout/settings/storage': typeof SidebarLayoutSettingsStorageRoute
  '/_sidebar-layout/settings/usage': typeof SidebarLayoutSettingsUsageRouteWithChildren
  '/_sidebar-layout/settings/white-label': typeof SidebarLayoutSettingsWhiteLabelRoute
  '/_sidebar-layout/shared-chat/$shareId': typeof SidebarLayoutSharedChatShareIdRoute
  '/embed/chart/$chartEmbedId': typeof EmbedChartChartEmbedIdRoute
  '/embed/map/$mapEmbedId': typeof EmbedMapMapEmbedIdRoute
  '/embed/story/$storyId': typeof EmbedStoryStoryIdRoute
  '/_sidebar-layout/_chat-layout/': typeof SidebarLayoutChatLayoutIndexRoute
  '/_sidebar-layout/feed/': typeof SidebarLayoutFeedIndexRoute
  '/_sidebar-layout/settings/': typeof SidebarLayoutSettingsIndexRoute
  '/_sidebar-layout/stories/': typeof SidebarLayoutStoriesIndexRoute
  '/_sidebar-layout/settings/organization/members': typeof SidebarLayoutSettingsOrganizationMembersRoute
  '/_sidebar-layout/settings/project/agent': typeof SidebarLayoutSettingsProjectAgentRoute
  '/_sidebar-layout/settings/project/budgets': typeof SidebarLayoutSettingsProjectBudgetsRoute
  '/_sidebar-layout/settings/project/integrations': typeof SidebarLayoutSettingsProjectIntegrationsRouteWithChildren
  '/_sidebar-layout/settings/project/mattermost': typeof SidebarLayoutSettingsProjectMattermostRoute
  '/_sidebar-layout/settings/project/mcp': typeof SidebarLayoutSettingsProjectMcpRoute
  '/_sidebar-layout/settings/project/mcp-endpoint': typeof SidebarLayoutSettingsProjectMcpEndpointRoute
  '/_sidebar-layout/settings/project/mcp-servers': typeof SidebarLayoutSettingsProjectMcpServersRoute
  '/_sidebar-layout/settings/project/models': typeof SidebarLayoutSettingsProjectModelsRoute
  '/_sidebar-layout/settings/project/slack': typeof SidebarLayoutSettingsProjectSlackRoute
  '/_sidebar-layout/settings/project/team': typeof SidebarLayoutSettingsProjectTeamRoute
  '/_sidebar-layout/settings/project/teams': typeof SidebarLayoutSettingsProjectTeamsRoute
  '/_sidebar-layout/settings/project/telegram': typeof SidebarLayoutSettingsProjectTelegramRoute
  '/_sidebar-layout/settings/project/whatsapp': typeof SidebarLayoutSettingsProjectWhatsappRoute
  '/_sidebar-layout/stories/shared/$shareId': typeof SidebarLayoutStoriesSharedShareIdRoute
  '/_sidebar-layout/stories/standalone/$storyId': typeof SidebarLayoutStoriesStandaloneStoryIdRoute
  '/_sidebar-layout/settings/organization/': typeof SidebarLayoutSettingsOrganizationIndexRoute
  '/_sidebar-layout/settings/project/': typeof SidebarLayoutSettingsProjectIndexRoute
  '/_sidebar-layout/settings/project/integrations/$integrationId': typeof SidebarLayoutSettingsProjectIntegrationsIntegrationIdRoute
  '/_sidebar-layout/settings/usage/replay/$chatId': typeof SidebarLayoutSettingsUsageReplayChatIdRoute
  '/_sidebar-layout/stories/preview/$chatId/$storySlug': typeof SidebarLayoutStoriesPreviewChatIdStorySlugRoute
  '/_sidebar-layout/settings/project/integrations/': typeof SidebarLayoutSettingsProjectIntegrationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/consent'
    | '/embed'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/settings'
    | '/$chatId'
    | '/automations/$automationId'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/context-explorer'
    | '/settings/enterprise'
    | '/settings/git'
    | '/settings/logs'
    | '/settings/mcp-endpoint'
    | '/settings/memory'
    | '/settings/organization'
    | '/settings/project'
    | '/settings/recommendations'
    | '/settings/storage'
    | '/settings/usage'
    | '/settings/white-label'
    | '/shared-chat/$shareId'
    | '/embed/chart/$chartEmbedId'
    | '/embed/map/$mapEmbedId'
    | '/embed/story/$storyId'
    | '/feed/'
    | '/settings/'
    | '/stories/'
    | '/settings/organization/members'
    | '/settings/project/agent'
    | '/settings/project/budgets'
    | '/settings/project/integrations'
    | '/settings/project/mattermost'
    | '/settings/project/mcp'
    | '/settings/project/mcp-endpoint'
    | '/settings/project/mcp-servers'
    | '/settings/project/models'
    | '/settings/project/slack'
    | '/settings/project/team'
    | '/settings/project/teams'
    | '/settings/project/telegram'
    | '/settings/project/whatsapp'
    | '/stories/shared/$shareId'
    | '/stories/standalone/$storyId'
    | '/settings/organization/'
    | '/settings/project/'
    | '/settings/project/integrations/$integrationId'
    | '/settings/usage/replay/$chatId'
    | '/stories/preview/$chatId/$storySlug'
    | '/settings/project/integrations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/consent'
    | '/embed'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/$chatId'
    | '/automations/$automationId'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/context-explorer'
    | '/settings/enterprise'
    | '/settings/git'
    | '/settings/logs'
    | '/settings/mcp-endpoint'
    | '/settings/memory'
    | '/settings/recommendations'
    | '/settings/storage'
    | '/settings/usage'
    | '/settings/white-label'
    | '/shared-chat/$shareId'
    | '/embed/chart/$chartEmbedId'
    | '/embed/map/$mapEmbedId'
    | '/embed/story/$storyId'
    | '/feed'
    | '/settings'
    | '/stories'
    | '/settings/organization/members'
    | '/settings/project/agent'
    | '/settings/project/budgets'
    | '/settings/project/mattermost'
    | '/settings/project/mcp'
    | '/settings/project/mcp-endpoint'
    | '/settings/project/mcp-servers'
    | '/settings/project/models'
    | '/settings/project/slack'
    | '/settings/project/team'
    | '/settings/project/teams'
    | '/settings/project/telegram'
    | '/settings/project/whatsapp'
    | '/stories/shared/$shareId'
    | '/stories/standalone/$storyId'
    | '/settings/organization'
    | '/settings/project'
    | '/settings/project/integrations/$integrationId'
    | '/settings/usage/replay/$chatId'
    | '/stories/preview/$chatId/$storySlug'
    | '/settings/project/integrations'
  id:
    | '__root__'
    | '/_sidebar-layout'
    | '/consent'
    | '/embed'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_sidebar-layout/_chat-layout'
    | '/_sidebar-layout/settings'
    | '/_sidebar-layout/_chat-layout/$chatId'
    | '/_sidebar-layout/automations/$automationId'
    | '/_sidebar-layout/settings/account'
    | '/_sidebar-layout/settings/appearance'
    | '/_sidebar-layout/settings/context-explorer'
    | '/_sidebar-layout/settings/enterprise'
    | '/_sidebar-layout/settings/git'
    | '/_sidebar-layout/settings/logs'
    | '/_sidebar-layout/settings/mcp-endpoint'
    | '/_sidebar-layout/settings/memory'
    | '/_sidebar-layout/settings/organization'
    | '/_sidebar-layout/settings/project'
    | '/_sidebar-layout/settings/recommendations'
    | '/_sidebar-layout/settings/storage'
    | '/_sidebar-layout/settings/usage'
    | '/_sidebar-layout/settings/white-label'
    | '/_sidebar-layout/shared-chat/$shareId'
    | '/embed/chart/$chartEmbedId'
    | '/embed/map/$mapEmbedId'
    | '/embed/story/$storyId'
    | '/_sidebar-layout/_chat-layout/'
    | '/_sidebar-layout/feed/'
    | '/_sidebar-layout/settings/'
    | '/_sidebar-layout/stories/'
    | '/_sidebar-layout/settings/organization/members'
    | '/_sidebar-layout/settings/project/agent'
    | '/_sidebar-layout/settings/project/budgets'
    | '/_sidebar-layout/settings/project/integrations'
    | '/_sidebar-layout/settings/project/mattermost'
    | '/_sidebar-layout/settings/project/mcp'
    | '/_sidebar-layout/settings/project/mcp-endpoint'
    | '/_sidebar-layout/settings/project/mcp-servers'
    | '/_sidebar-layout/settings/project/models'
    | '/_sidebar-layout/settings/project/slack'
    | '/_sidebar-layout/settings/project/team'
    | '/_sidebar-layout/settings/project/teams'
    | '/_sidebar-layout/settings/project/telegram'
    | '/_sidebar-layout/settings/project/whatsapp'
    | '/_sidebar-layout/stories/shared/$shareId'
    | '/_sidebar-layout/stories/standalone/$storyId'
    | '/_sidebar-layout/settings/organization/'
    | '/_sidebar-layout/settings/project/'
    | '/_sidebar-layout/settings/project/integrations/$integrationId'
    | '/_sidebar-layout/settings/usage/replay/$chatId'
    | '/_sidebar-layout/stories/preview/$chatId/$storySlug'
    | '/_sidebar-layout/settings/project/integrations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SidebarLayoutRoute: typeof SidebarLayoutRouteWithChildren
  ConsentRoute: typeof ConsentRoute
  EmbedRoute: typeof EmbedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed': {
      id: '/embed'
      path: '/embed'
      fullPath: '/embed'
      preLoaderRoute: typeof EmbedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebar-layout': {
      id: '/_sidebar-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SidebarLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebar-layout/settings': {
      id: '/_sidebar-layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SidebarLayoutSettingsRouteImport
      parentRoute: typeof SidebarLayoutRoute
    }
    '/_sidebar-layout/_chat-layout': {
      id: '/_sidebar-layout/_chat-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SidebarLayoutChatLayoutRouteImport
      parentRoute: typeof SidebarLayoutRoute
    }
    '/_sidebar-layout/stories/': {
      id: '/_sidebar-layout/stories/'
      path: '/stories'
      fullPath: '/stories/'
      preLoaderRoute: typeof SidebarLayoutStoriesIndexRouteImport
      parentRoute: typeof SidebarLayoutRoute
    }
    '/_sidebar-layout/settings/': {
      id: '/_sidebar-layout/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SidebarLayoutSettingsIndexRouteImport
      parentRoute: typeof SidebarLayoutSettingsRoute
    }
    '/_sidebar-layout/feed/': {
      id: '/_sidebar-layout/feed/'
      path: '/feed'
      fullPath: '/feed/'
      preLoaderRoute: typeof SidebarLayoutFeedIndexRouteImport
      parentRoute: typeof SidebarLayoutRoute
    }
    '/_sidebar-layout/_chat-layout/': {
      id: '/_sidebar-layout/_chat-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SidebarLayoutChatLayoutIndexRouteImport
      parentRoute: typeof SidebarLayoutChatLayoutRoute
    }
    '/embed/story/$storyId': {
      id: '/embed/story/$storyId'
      path: '/story/$storyId'
      fullPath: '/embed/story/$storyId'
      preLoaderRoute: typeof EmbedStoryStoryIdRouteImport
      parentRoute: typeof EmbedRoute
    }
    '/embed/map/$mapEmbedId': {
      id: '/embed/map/$mapEmbedId'
      path: '/map/$mapEmbedId'
      fullPath: '/embed/map/$mapEmbedId'
      preLoaderRoute: typeof EmbedMapMapEmbedIdRouteImport
      parentRoute: typeof EmbedRoute
    }
    '/embed/chart/$chartEmbedId': {
      id: '/embed/chart/$chartEmbedId'
      path: '/chart/$chartEmbedId'
      fullPath: '/embed/chart/$chartEmbedId'
      preLoaderRoute: typeof EmbedChartChartEmbedIdRouteImport
      parentRoute: typeof EmbedRoute
    }
    '/_sidebar-layout/shared-chat/$shareId': {
      id: '/_sidebar-layout/shared-chat/$shareId'
      path: '/shared-chat/$shareId'
      fullPath: '/shared-chat/$shareId'
      preLoaderRoute: typeof SidebarLayoutSharedChatShareIdRouteImport
      parentRoute: typeof SidebarLayoutRoute
    }
    '/_sidebar-layout/settings/white-label': {
      id: '/_sidebar-layout/settings/white-label'
      path: '/white-label'
      fullPath: '/settings/white-label'
      preLoaderRoute: typeof SidebarLayoutSettingsWhiteLabelRouteImport
      parentRoute: typeof SidebarLayoutSettingsRoute
    }
    '/_sidebar-layout/settings/usage': {
      id: '/_sidebar-layout/settings/usage'
      path: '/usage'
      fullPath: '/settings/usage'
      preLoaderRoute: typeof SidebarLayoutSettingsUsageRouteImport
      parentRoute: typeof SidebarLayoutSettingsRoute
    }
    '/_sidebar-layout/settings/storage': {
      id: '/_sidebar-layout/settings/storage'
      path: '/storage'
      fullPath: '/settings/storage'
      preLoaderRoute: typeof SidebarLayoutSettingsStorageRouteImport
      parentRoute: typeof SidebarLayoutSettingsRoute
    }
    '/_sidebar-layout/settings/recommendations': {
      id: '/_sidebar-layout/settings/recommendations'
      path: '/recommendations'
      fullPath: '/settings/recommendations'
      preLoaderRoute: typeof SidebarLayoutSettingsRecommendationsRouteImport
      parentRoute: typeof SidebarLayoutSettingsRoute
    }
    '/_sidebar-layout/settings/project': {
      id: '/_sidebar-layout/settings/project'
      path: '/project'
      fullPath: '/settings/project'
      preLoaderRoute: typeof SidebarLayoutSettingsProjectRouteImport
      parentRoute: typeof SidebarLayoutSettingsRoute
    }
    '/_sidebar-layout/settings/organization': {
      id: '/_sidebar-layout/settings/organization'
      path: '/organization'
      fullPath: '/settings/organization'
      preLoaderRoute: typeof SidebarLayoutSettingsOrganizationRouteImport
      parentRoute: typeof SidebarLayoutSettingsRoute
    }
    '/_sidebar-layout/settings/memory': {
      id: '/_sidebar-layout/settings/memory'
      path: '/memory'
      fullPath: '/settings/memory'
      preLoaderRoute: typeof SidebarLayoutSettingsMemoryRouteImport
      parentRoute: typeof SidebarLayoutSettingsRoute
    }
    '/_sidebar-layout/settings/mcp-endpoint': {
      id: '/_sidebar-layout/settings/mcp-endpoint'
      path: '/mcp-endpoint'
      fullPath: '/settings/mcp-endpoint'
      preLoaderRoute: typeof SidebarLayoutSettingsMcpEndpointRouteImport
      parentRoute: typeof SidebarLayoutSettingsRoute
    }
    '/_sidebar-layout/settings/logs': {
      id: '/_sidebar-layout/settings/logs'
      path: '/logs'
      fullPath: '/settings/logs'
      preLoaderRoute: typeof SidebarLayoutSettingsLogsRouteImport
      parentRoute: typeof SidebarLayoutSettingsRoute
    }
    '/_sidebar-layout/settings/git': {
      id: '/_sidebar-layout/settings/git'
      path: '/git'
      fullPath: '/settings/git'
      preLoaderRoute: typeof SidebarLayoutSettingsGitRouteImport
      parentRoute: typeof SidebarLayoutSettingsRoute
    }
    '/_sidebar-layout/settings/enterprise': {
      id: '/_sidebar-layout/settings/enterprise'
      path: '/enterprise'
      fullPath: '/settings/enterprise'
      preLoaderRoute: typeof SidebarLayoutSettingsEnterpriseRouteImport
      parentRoute: typeof SidebarLayoutSettingsRoute
    }
    '/_sidebar-layout/settings/context-explorer': {
      id: '/_sidebar-layout/settings/context-explorer'
      path: '/context-explorer'
      fullPath: '/settings/context-explorer'
      preLoaderRoute: typeof SidebarLayoutSettingsContextExplorerRouteImport
      parentRoute: typeof SidebarLayoutSettingsRoute
    }
    '/_sidebar-layout/settings/appearance': {
      id: '/_sidebar-layout/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SidebarLayoutSettingsAppearanceRouteImport
      parentRoute: typeof SidebarLayoutSettingsRoute
    }
    '/_sidebar-layout/settings/account': {
      id: '/_sidebar-layout/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof SidebarLayoutSettingsAccountRouteImport
      parentRoute: typeof SidebarLayoutSettingsRoute
    }
    '/_sidebar-layout/automations/$automationId': {
      id: '/_sidebar-layout/automations/$automationId'
      path: '/automations/$automationId'
      fullPath: '/automations/$automationId'
      preLoaderRoute: typeof SidebarLayoutAutomationsAutomationIdRouteImport
      parentRoute: typeof SidebarLayoutRoute
    }
    '/_sidebar-layout/_chat-layout/$chatId': {
      id: '/_sidebar-layout/_chat-layout/$chatId'
      path: '/$chatId'
      fullPath: '/$chatId'
      preLoaderRoute: typeof SidebarLayoutChatLayoutChatIdRouteImport
      parentRoute: typeof SidebarLayoutChatLayoutRoute
    }
    '/_sidebar-layout/settings/project/': {
      id: '/_sidebar-layout/settings/project/'
      path: '/'
      fullPath: '/settings/project/'
      preLoaderRoute: typeof SidebarLayoutSettingsProjectIndexRouteImport
      parentRoute: typeof SidebarLayoutSettingsProjectRoute
    }
    '/_sidebar-layout/settings/organization/': {
      id: '/_sidebar-layout/settings/organization/'
      path: '/'
      fullPath: '/settings/organization/'
      preLoaderRoute: typeof SidebarLayoutSettingsOrganizationIndexRouteImport
      parentRoute: typeof SidebarLayoutSettingsOrganizationRoute
    }
    '/_sidebar-layout/stories/standalone/$storyId': {
      id: '/_sidebar-layout/stories/standalone/$storyId'
      path: '/stories/standalone/$storyId'
      fullPath: '/stories/standalone/$storyId'
      preLoaderRoute: typeof SidebarLayoutStoriesStandaloneStoryIdRouteImport
      parentRoute: typeof SidebarLayoutRoute
    }
    '/_sidebar-layout/stories/shared/$shareId': {
      id: '/_sidebar-layout/stories/shared/$shareId'
      path: '/stories/shared/$shareId'
      fullPath: '/stories/shared/$shareId'
      preLoaderRoute: typeof SidebarLayoutStoriesSharedShareIdRouteImport
      parentRoute: typeof SidebarLayoutRoute
    }
    '/_sidebar-layout/settings/project/whatsapp': {
      id: '/_sidebar-layout/settings/project/whatsapp'
      path: '/whatsapp'
      fullPath: '/settings/project/whatsapp'
      preLoaderRoute: typeof SidebarLayoutSettingsProjectWhatsappRouteImport
      parentRoute: typeof SidebarLayoutSettingsProjectRoute
    }
    '/_sidebar-layout/settings/project/telegram': {
      id: '/_sidebar-layout/settings/project/telegram'
      path: '/telegram'
      fullPath: '/settings/project/telegram'
      preLoaderRoute: typeof SidebarLayoutSettingsProjectTelegramRouteImport
      parentRoute: typeof SidebarLayoutSettingsProjectRoute
    }
    '/_sidebar-layout/settings/project/teams': {
      id: '/_sidebar-layout/settings/project/teams'
      path: '/teams'
      fullPath: '/settings/project/teams'
      preLoaderRoute: typeof SidebarLayoutSettingsProjectTeamsRouteImport
      parentRoute: typeof SidebarLayoutSettingsProjectRoute
    }
    '/_sidebar-layout/settings/project/team': {
      id: '/_sidebar-layout/settings/project/team'
      path: '/team'
      fullPath: '/settings/project/team'
      preLoaderRoute: typeof SidebarLayoutSettingsProjectTeamRouteImport
      parentRoute: typeof SidebarLayoutSettingsProjectRoute
    }
    '/_sidebar-layout/settings/project/slack': {
      id: '/_sidebar-layout/settings/project/slack'
      path: '/slack'
      fullPath: '/settings/project/slack'
      preLoaderRoute: typeof SidebarLayoutSettingsProjectSlackRouteImport
      parentRoute: typeof SidebarLayoutSettingsProjectRoute
    }
    '/_sidebar-layout/settings/project/models': {
      id: '/_sidebar-layout/settings/project/models'
      path: '/models'
      fullPath: '/settings/project/models'
      preLoaderRoute: typeof SidebarLayoutSettingsProjectModelsRouteImport
      parentRoute: typeof SidebarLayoutSettingsProjectRoute
    }
    '/_sidebar-layout/settings/project/mcp-servers': {
      id: '/_sidebar-layout/settings/project/mcp-servers'
      path: '/mcp-servers'
      fullPath: '/settings/project/mcp-servers'
      preLoaderRoute: typeof SidebarLayoutSettingsProjectMcpServersRouteImport
      parentRoute: typeof SidebarLayoutSettingsProjectRoute
    }
    '/_sidebar-layout/settings/project/mcp-endpoint': {
      id: '/_sidebar-layout/settings/project/mcp-endpoint'
      path: '/mcp-endpoint'
      fullPath: '/settings/project/mcp-endpoint'
      preLoaderRoute: typeof SidebarLayoutSettingsProjectMcpEndpointRouteImport
      parentRoute: typeof SidebarLayoutSettingsProjectRoute
    }
    '/_sidebar-layout/settings/project/mcp': {
      id: '/_sidebar-layout/settings/project/mcp'
      path: '/mcp'
      fullPath: '/settings/project/mcp'
      preLoaderRoute: typeof SidebarLayoutSettingsProjectMcpRouteImport
      parentRoute: typeof SidebarLayoutSettingsProjectRoute
    }
    '/_sidebar-layout/settings/project/mattermost': {
      id: '/_sidebar-layout/settings/project/mattermost'
      path: '/mattermost'
      fullPath: '/settings/project/mattermost'
      preLoaderRoute: typeof SidebarLayoutSettingsProjectMattermostRouteImport
      parentRoute: typeof SidebarLayoutSettingsProjectRoute
    }
    '/_sidebar-layout/settings/project/integrations': {
      id: '/_sidebar-layout/settings/project/integrations'
      path: '/integrations'
      fullPath: '/settings/project/integrations'
      preLoaderRoute: typeof SidebarLayoutSettingsProjectIntegrationsRouteImport
      parentRoute: typeof SidebarLayoutSettingsProjectRoute
    }
    '/_sidebar-layout/settings/project/budgets': {
      id: '/_sidebar-layout/settings/project/budgets'
      path: '/budgets'
      fullPath: '/settings/project/budgets'
      preLoaderRoute: typeof SidebarLayoutSettingsProjectBudgetsRouteImport
      parentRoute: typeof SidebarLayoutSettingsProjectRoute
    }
    '/_sidebar-layout/settings/project/agent': {
      id: '/_sidebar-layout/settings/project/agent'
      path: '/agent'
      fullPath: '/settings/project/agent'
      preLoaderRoute: typeof SidebarLayoutSettingsProjectAgentRouteImport
      parentRoute: typeof SidebarLayoutSettingsProjectRoute
    }
    '/_sidebar-layout/settings/organization/members': {
      id: '/_sidebar-layout/settings/organization/members'
      path: '/members'
      fullPath: '/settings/organization/members'
      preLoaderRoute: typeof SidebarLayoutSettingsOrganizationMembersRouteImport
      parentRoute: typeof SidebarLayoutSettingsOrganizationRoute
    }
    '/_sidebar-layout/settings/project/integrations/': {
      id: '/_sidebar-layout/settings/project/integrations/'
      path: '/'
      fullPath: '/settings/project/integrations/'
      preLoaderRoute: typeof SidebarLayoutSettingsProjectIntegrationsIndexRouteImport
      parentRoute: typeof SidebarLayoutSettingsProjectIntegrationsRoute
    }
    '/_sidebar-layout/stories/preview/$chatId/$storySlug': {
      id: '/_sidebar-layout/stories/preview/$chatId/$storySlug'
      path: '/stories/preview/$chatId/$storySlug'
      fullPath: '/stories/preview/$chatId/$storySlug'
      preLoaderRoute: typeof SidebarLayoutStoriesPreviewChatIdStorySlugRouteImport
      parentRoute: typeof SidebarLayoutRoute
    }
    '/_sidebar-layout/settings/usage/replay/$chatId': {
      id: '/_sidebar-layout/settings/usage/replay/$chatId'
      path: '/replay/$chatId'
      fullPath: '/settings/usage/replay/$chatId'
      preLoaderRoute: typeof SidebarLayoutSettingsUsageReplayChatIdRouteImport
      parentRoute: typeof SidebarLayoutSettingsUsageRoute
    }
    '/_sidebar-layout/settings/project/integrations/$integrationId': {
      id: '/_sidebar-layout/settings/project/integrations/$integrationId'
      path: '/$integrationId'
      fullPath: '/settings/project/integrations/$integrationId'
      preLoaderRoute: typeof SidebarLayoutSettingsProjectIntegrationsIntegrationIdRouteImport
      parentRoute: typeof SidebarLayoutSettingsProjectIntegrationsRoute
    }
  }
}

interface SidebarLayoutChatLayoutRouteChildren {
  SidebarLayoutChatLayoutChatIdRoute: typeof SidebarLayoutChatLayoutChatIdRoute
  SidebarLayoutChatLayoutIndexRoute: typeof SidebarLayoutChatLayoutIndexRoute
}

const SidebarLayoutChatLayoutRouteChildren: SidebarLayoutChatLayoutRouteChildren =
  {
    SidebarLayoutChatLayoutChatIdRoute: SidebarLayoutChatLayoutChatIdRoute,
    SidebarLayoutChatLayoutIndexRoute: SidebarLayoutChatLayoutIndexRoute,
  }

const SidebarLayoutChatLayoutRouteWithChildren =
  SidebarLayoutChatLayoutRoute._addFileChildren(
    SidebarLayoutChatLayoutRouteChildren,
  )

interface SidebarLayoutSettingsOrganizationRouteChildren {
  SidebarLayoutSettingsOrganizationMembersRoute: typeof SidebarLayoutSettingsOrganizationMembersRoute
  SidebarLayoutSettingsOrganizationIndexRoute: typeof SidebarLayoutSettingsOrganizationIndexRoute
}

const SidebarLayoutSettingsOrganizationRouteChildren: SidebarLayoutSettingsOrganizationRouteChildren =
  {
    SidebarLayoutSettingsOrganizationMembersRoute:
      SidebarLayoutSettingsOrganizationMembersRoute,
    SidebarLayoutSettingsOrganizationIndexRoute:
      SidebarLayoutSettingsOrganizationIndexRoute,
  }

const SidebarLayoutSettingsOrganizationRouteWithChildren =
  SidebarLayoutSettingsOrganizationRoute._addFileChildren(
    SidebarLayoutSettingsOrganizationRouteChildren,
  )

interface SidebarLayoutSettingsProjectIntegrationsRouteChildren {
  SidebarLayoutSettingsProjectIntegrationsIntegrationIdRoute: typeof SidebarLayoutSettingsProjectIntegrationsIntegrationIdRoute
  SidebarLayoutSettingsProjectIntegrationsIndexRoute: typeof SidebarLayoutSettingsProjectIntegrationsIndexRoute
}

const SidebarLayoutSettingsProjectIntegrationsRouteChildren: SidebarLayoutSettingsProjectIntegrationsRouteChildren =
  {
    SidebarLayoutSettingsProjectIntegrationsIntegrationIdRoute:
      SidebarLayoutSettingsProjectIntegrationsIntegrationIdRoute,
    SidebarLayoutSettingsProjectIntegrationsIndexRoute:
      SidebarLayoutSettingsProjectIntegrationsIndexRoute,
  }

const SidebarLayoutSettingsProjectIntegrationsRouteWithChildren =
  SidebarLayoutSettingsProjectIntegrationsRoute._addFileChildren(
    SidebarLayoutSettingsProjectIntegrationsRouteChildren,
  )

interface SidebarLayoutSettingsProjectRouteChildren {
  SidebarLayoutSettingsProjectAgentRoute: typeof SidebarLayoutSettingsProjectAgentRoute
  SidebarLayoutSettingsProjectBudgetsRoute: typeof SidebarLayoutSettingsProjectBudgetsRoute
  SidebarLayoutSettingsProjectIntegrationsRoute: typeof SidebarLayoutSettingsProjectIntegrationsRouteWithChildren
  SidebarLayoutSettingsProjectMattermostRoute: typeof SidebarLayoutSettingsProjectMattermostRoute
  SidebarLayoutSettingsProjectMcpRoute: typeof SidebarLayoutSettingsProjectMcpRoute
  SidebarLayoutSettingsProjectMcpEndpointRoute: typeof SidebarLayoutSettingsProjectMcpEndpointRoute
  SidebarLayoutSettingsProjectMcpServersRoute: typeof SidebarLayoutSettingsProjectMcpServersRoute
  SidebarLayoutSettingsProjectModelsRoute: typeof SidebarLayoutSettingsProjectModelsRoute
  SidebarLayoutSettingsProjectSlackRoute: typeof SidebarLayoutSettingsProjectSlackRoute
  SidebarLayoutSettingsProjectTeamRoute: typeof SidebarLayoutSettingsProjectTeamRoute
  SidebarLayoutSettingsProjectTeamsRoute: typeof SidebarLayoutSettingsProjectTeamsRoute
  SidebarLayoutSettingsProjectTelegramRoute: typeof SidebarLayoutSettingsProjectTelegramRoute
  SidebarLayoutSettingsProjectWhatsappRoute: typeof SidebarLayoutSettingsProjectWhatsappRoute
  SidebarLayoutSettingsProjectIndexRoute: typeof SidebarLayoutSettingsProjectIndexRoute
}

const SidebarLayoutSettingsProjectRouteChildren: SidebarLayoutSettingsProjectRouteChildren =
  {
    SidebarLayoutSettingsProjectAgentRoute:
      SidebarLayoutSettingsProjectAgentRoute,
    SidebarLayoutSettingsProjectBudgetsRoute:
      SidebarLayoutSettingsProjectBudgetsRoute,
    SidebarLayoutSettingsProjectIntegrationsRoute:
      SidebarLayoutSettingsProjectIntegrationsRouteWithChildren,
    SidebarLayoutSettingsProjectMattermostRoute:
      SidebarLayoutSettingsProjectMattermostRoute,
    SidebarLayoutSettingsProjectMcpRoute: SidebarLayoutSettingsProjectMcpRoute,
    SidebarLayoutSettingsProjectMcpEndpointRoute:
      SidebarLayoutSettingsProjectMcpEndpointRoute,
    SidebarLayoutSettingsProjectMcpServersRoute:
      SidebarLayoutSettingsProjectMcpServersRoute,
    SidebarLayoutSettingsProjectModelsRoute:
      SidebarLayoutSettingsProjectModelsRoute,
    SidebarLayoutSettingsProjectSlackRoute:
      SidebarLayoutSettingsProjectSlackRoute,
    SidebarLayoutSettingsProjectTeamRoute:
      SidebarLayoutSettingsProjectTeamRoute,
    SidebarLayoutSettingsProjectTeamsRoute:
      SidebarLayoutSettingsProjectTeamsRoute,
    SidebarLayoutSettingsProjectTelegramRoute:
      SidebarLayoutSettingsProjectTelegramRoute,
    SidebarLayoutSettingsProjectWhatsappRoute:
      SidebarLayoutSettingsProjectWhatsappRoute,
    SidebarLayoutSettingsProjectIndexRoute:
      SidebarLayoutSettingsProjectIndexRoute,
  }

const SidebarLayoutSettingsProjectRouteWithChildren =
  SidebarLayoutSettingsProjectRoute._addFileChildren(
    SidebarLayoutSettingsProjectRouteChildren,
  )

interface SidebarLayoutSettingsUsageRouteChildren {
  SidebarLayoutSettingsUsageReplayChatIdRoute: typeof SidebarLayoutSettingsUsageReplayChatIdRoute
}

const SidebarLayoutSettingsUsageRouteChildren: SidebarLayoutSettingsUsageRouteChildren =
  {
    SidebarLayoutSettingsUsageReplayChatIdRoute:
      SidebarLayoutSettingsUsageReplayChatIdRoute,
  }

const SidebarLayoutSettingsUsageRouteWithChildren =
  SidebarLayoutSettingsUsageRoute._addFileChildren(
    SidebarLayoutSettingsUsageRouteChildren,
  )

interface SidebarLayoutSettingsRouteChildren {
  SidebarLayoutSettingsAccountRoute: typeof SidebarLayoutSettingsAccountRoute
  SidebarLayoutSettingsAppearanceRoute: typeof SidebarLayoutSettingsAppearanceRoute
  SidebarLayoutSettingsContextExplorerRoute: typeof SidebarLayoutSettingsContextExplorerRoute
  SidebarLayoutSettingsEnterpriseRoute: typeof SidebarLayoutSettingsEnterpriseRoute
  SidebarLayoutSettingsGitRoute: typeof SidebarLayoutSettingsGitRoute
  SidebarLayoutSettingsLogsRoute: typeof SidebarLayoutSettingsLogsRoute
  SidebarLayoutSettingsMcpEndpointRoute: typeof SidebarLayoutSettingsMcpEndpointRoute
  SidebarLayoutSettingsMemoryRoute: typeof SidebarLayoutSettingsMemoryRoute
  SidebarLayoutSettingsOrganizationRoute: typeof SidebarLayoutSettingsOrganizationRouteWithChildren
  SidebarLayoutSettingsProjectRoute: typeof SidebarLayoutSettingsProjectRouteWithChildren
  SidebarLayoutSettingsRecommendationsRoute: typeof SidebarLayoutSettingsRecommendationsRoute
  SidebarLayoutSettingsStorageRoute: typeof SidebarLayoutSettingsStorageRoute
  SidebarLayoutSettingsUsageRoute: typeof SidebarLayoutSettingsUsageRouteWithChildren
  SidebarLayoutSettingsWhiteLabelRoute: typeof SidebarLayoutSettingsWhiteLabelRoute
  SidebarLayoutSettingsIndexRoute: typeof SidebarLayoutSettingsIndexRoute
}

const SidebarLayoutSettingsRouteChildren: SidebarLayoutSettingsRouteChildren = {
  SidebarLayoutSettingsAccountRoute: SidebarLayoutSettingsAccountRoute,
  SidebarLayoutSettingsAppearanceRoute: SidebarLayoutSettingsAppearanceRoute,
  SidebarLayoutSettingsContextExplorerRoute:
    SidebarLayoutSettingsContextExplorerRoute,
  SidebarLayoutSettingsEnterpriseRoute: SidebarLayoutSettingsEnterpriseRoute,
  SidebarLayoutSettingsGitRoute: SidebarLayoutSettingsGitRoute,
  SidebarLayoutSettingsLogsRoute: SidebarLayoutSettingsLogsRoute,
  SidebarLayoutSettingsMcpEndpointRoute: SidebarLayoutSettingsMcpEndpointRoute,
  SidebarLayoutSettingsMemoryRoute: SidebarLayoutSettingsMemoryRoute,
  SidebarLayoutSettingsOrganizationRoute:
    SidebarLayoutSettingsOrganizationRouteWithChildren,
  SidebarLayoutSettingsProjectRoute:
    SidebarLayoutSettingsProjectRouteWithChildren,
  SidebarLayoutSettingsRecommendationsRoute:
    SidebarLayoutSettingsRecommendationsRoute,
  SidebarLayoutSettingsStorageRoute: SidebarLayoutSettingsStorageRoute,
  SidebarLayoutSettingsUsageRoute: SidebarLayoutSettingsUsageRouteWithChildren,
  SidebarLayoutSettingsWhiteLabelRoute: SidebarLayoutSettingsWhiteLabelRoute,
  SidebarLayoutSettingsIndexRoute: SidebarLayoutSettingsIndexRoute,
}

const SidebarLayoutSettingsRouteWithChildren =
  SidebarLayoutSettingsRoute._addFileChildren(
    SidebarLayoutSettingsRouteChildren,
  )

interface SidebarLayoutRouteChildren {
  SidebarLayoutChatLayoutRoute: typeof SidebarLayoutChatLayoutRouteWithChildren
  SidebarLayoutSettingsRoute: typeof SidebarLayoutSettingsRouteWithChildren
  SidebarLayoutAutomationsAutomationIdRoute: typeof SidebarLayoutAutomationsAutomationIdRoute
  SidebarLayoutSharedChatShareIdRoute: typeof SidebarLayoutSharedChatShareIdRoute
  SidebarLayoutFeedIndexRoute: typeof SidebarLayoutFeedIndexRoute
  SidebarLayoutStoriesIndexRoute: typeof SidebarLayoutStoriesIndexRoute
  SidebarLayoutStoriesSharedShareIdRoute: typeof SidebarLayoutStoriesSharedShareIdRoute
  SidebarLayoutStoriesStandaloneStoryIdRoute: typeof SidebarLayoutStoriesStandaloneStoryIdRoute
  SidebarLayoutStoriesPreviewChatIdStorySlugRoute: typeof SidebarLayoutStoriesPreviewChatIdStorySlugRoute
}

const SidebarLayoutRouteChildren: SidebarLayoutRouteChildren = {
  SidebarLayoutChatLayoutRoute: SidebarLayoutChatLayoutRouteWithChildren,
  SidebarLayoutSettingsRoute: SidebarLayoutSettingsRouteWithChildren,
  SidebarLayoutAutomationsAutomationIdRoute:
    SidebarLayoutAutomationsAutomationIdRoute,
  SidebarLayoutSharedChatShareIdRoute: SidebarLayoutSharedChatShareIdRoute,
  SidebarLayoutFeedIndexRoute: SidebarLayoutFeedIndexRoute,
  SidebarLayoutStoriesIndexRoute: SidebarLayoutStoriesIndexRoute,
  SidebarLayoutStoriesSharedShareIdRoute:
    SidebarLayoutStoriesSharedShareIdRoute,
  SidebarLayoutStoriesStandaloneStoryIdRoute:
    SidebarLayoutStoriesStandaloneStoryIdRoute,
  SidebarLayoutStoriesPreviewChatIdStorySlugRoute:
    SidebarLayoutStoriesPreviewChatIdStorySlugRoute,
}

const SidebarLayoutRouteWithChildren = SidebarLayoutRoute._addFileChildren(
  SidebarLayoutRouteChildren,
)

interface EmbedRouteChildren {
  EmbedChartChartEmbedIdRoute: typeof EmbedChartChartEmbedIdRoute
  EmbedMapMapEmbedIdRoute: typeof EmbedMapMapEmbedIdRoute
  EmbedStoryStoryIdRoute: typeof EmbedStoryStoryIdRoute
}

const EmbedRouteChildren: EmbedRouteChildren = {
  EmbedChartChartEmbedIdRoute: EmbedChartChartEmbedIdRoute,
  EmbedMapMapEmbedIdRoute: EmbedMapMapEmbedIdRoute,
  EmbedStoryStoryIdRoute: EmbedStoryStoryIdRoute,
}

const EmbedRouteWithChildren = EmbedRoute._addFileChildren(EmbedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SidebarLayoutRoute: SidebarLayoutRouteWithChildren,
  ConsentRoute: ConsentRoute,
  EmbedRoute: EmbedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
